get-google-chrome: do not create empty packages if /usr/bin/ar not exist

diff --git a/get-google-chrome/stuff/get-google-chrome b/get-google-chrome/stuff/get-google-chrome
--- a/get-google-chrome/stuff/get-google-chrome
+++ b/get-google-chrome/stuff/get-google-chrome
@@ -34,6 +34,17 @@ if [ ! -f $DEBPKG ]; then
 	exit 1
 fi
 
+# Install binutils(ar) pkg
+if [ ! -d /var/lib/tazpkg/installed/binutils ]; then
+    tazpkg get-install binutils
+fi
+if [ ! -f /usr/bin/ar ]; then
+    cd $CUR_DIR
+    rm -rf $TEMP_DIR
+    echo "Could not extract $DEBPKG. Exiting."
+    exit 1
+fi
+
 ar x $DEBPKG control.tar.gz data.tar.lzma && lzma d data.tar.lzma -so | tar xf -
 tar xzf control.tar.gz ./control
 VERSION=`sed -n 's/Version:\ *//p' control`
