Update some WEB_SITE

diff --git a/syslinux/stuff/iso2exe/init b/syslinux/stuff/iso2exe/init
--- a/syslinux/stuff/iso2exe/init
+++ b/syslinux/stuff/iso2exe/init
@@ -68,7 +68,7 @@ tinydialog()
 				esac
 			done ;;
 		--menu|--radiolist)
-			[ "$1" == "--menu" ] && shft=2 || shft=3
+			[ "$1" = "--menu" ] && shft=2 || shft=3
 			label=""
 			[ "$2" ] && label="\n$2"
 			shift 5
@@ -138,7 +138,7 @@ gettazboot()
 
 checkmagic()
 {
-	[ -s $1 ] && [ $(getarg magic) == $(get 18 $1 2) ]
+	[ -s $1 ] && [ $(getarg magic) = $(get 18 $1 2) ]
 }
 
 getiso()
@@ -667,7 +667,7 @@ customsector()
 hascustomconf()
 {
 	[ "$(ddq bs=2k skip=$(customsector) if="/mnt/$ISO" | ddq bs=1 count=6)" \
-	  == "#!boot" ]
+	  = "#!boot" ]
 }
 
 gotcustomconf()
@@ -705,7 +705,7 @@ isomd5()
 {
 	dotwait "Checking iso image"
 	[ "$(ddq if=/mnt/$ISO bs=2k skip=16 \
-	     count=$(($(get 32848 /mnt/$ISO 4)-16)) | md5sum)" == \
+	     count=$(($(get 32848 /mnt/$ISO 4)-16)) | md5sum)" = \
 	  "$(ddq if=/mnt/$ISO bs=16 count=1 skip=2047 | od -N 16 -t x1 -An | \
 	     sed 's/ //g')  -" ] && echo "OK" || echo "ERROR"
 	echo -en "\rChecking iso hybrid boot..."
@@ -730,7 +730,7 @@ isomd5()
 			*)	  break ;;
 			esac
 		done | md5sum | cut -c1-32)"
-		[ "$md5" == "$(cat $TMP)" ] && echo "OK" || echo "ERROR"
+		[ "$md5" = "$(cat $TMP)" ] && echo "OK" || echo "ERROR"
 		rm -f $TMP
 	fi
 	rm -f /tmp/wait
@@ -738,7 +738,7 @@ isomd5()
 	read n
 }
 
-if [ "$1" == "--build" ]; then	#install-begin
+if [ "$1" = "--build" ]; then	#install-begin
 	cp $0 $0.tmp
 	uuencode -m - < ifmem.bin | sed -e 's|^[ \t]*||;s|[ \t]*###.*||' \
 	  -e 's| *;;|;;|;s|\t\t*|\t|g' \
@@ -1130,7 +1130,7 @@ flavdata()
 
 hasflavinfo()
 {
-	[ "$(flavdata | ddq bs=1 count=7)" == "0707010" ] &&
+	[ "$(flavdata | ddq bs=1 count=7)" = "0707010" ] &&
 	echo -en "\"$1\"	\"$2\""
 }
 
