taziso, iso2exe.sh: add custom config support ; awstat-hotspot, awesome, avant-window-navigator: update pre/post_install

diff --git a/syslinux/stuff/iso2exe/taziso b/syslinux/stuff/iso2exe/taziso
--- a/syslinux/stuff/iso2exe/taziso
+++ b/syslinux/stuff/iso2exe/taziso
@@ -11,8 +11,8 @@ ddq()
 
 get()
 {
-	od -v -j $1 -N ${4:-${3:-2}} -t u${3:-2} -w${3:-2} -An $2 2>/dev/null ||
-	hexdump -v -s $1 -n ${4:-${3:-2}} -e "\"\" 1/${3:-2} \" %d\n\"" $2
+	od -v -j $1 -N ${4:-${3:-2}} -t u${3:-2} -w${3:-2} -An "$2" 2>/dev/null ||
+	hexdump -v -s $1 -n ${4:-${3:-2}} -e "\"\" 1/${3:-2} \" %d\n\"" "$2"
 }
 
 bytes2bin()
@@ -32,14 +32,14 @@ words2bin()
 gettazboot()
 {
 	echo "Creating $(basename $1) ..."
-	O=$(($(get 64 $ISO) - 0xC0))
-	L=$(($(get 20 $ISO) - 0xC0 - $(get 24 $ISO) - $O))
+	O=$(($(get 64 "$ISO") - 0xC0))
+	L=$(($(get 20 "$ISO") - 0xC0 - $(get 24 "$ISO") - $O))
 	S=$((32+$L))
 	P=$((($S+511)/512))
 	E=$((4096-(32*$P)))
 	words2bin 0x5A4D $(($S%512)) $P 0 2 $E -1 $((${2:-0}-16)) \
 			-2 0 256 -16 28 0x6C53 0x5469 0x7A61 > $1
-	ddq bs=1 count=$L skip=$(echo $O) if=$ISO >> $1
+	ddq bs=1 count=$L skip=$(echo $O) if="$ISO" >> $1
 }
 
 uncpio()
@@ -461,10 +461,10 @@ See http://diddy.boot-land.net/grub4dos/files/README_GRUB4DOS.txt
 and http://xpt.sourceforge.net/techdocs/nix/disk/boot/boot07-GrubForDosInfo/ar01s03.html
 EOT
 	( cd $mnt ; echo 'See \slitaz\boot\install.txt to launch SliTaz.' | \
-	  zip -zr9 $(basename $ISO .iso).zip slitaz )
+	  zip -zr9 $(basename "$ISO" .iso).zip slitaz )
 	[ "$(which advzip)" ] && advzip -z4 $mnt/*.zip
 	mv $mnt/*.zip .
-	ls -l $PWD/$(basename $ISO .iso).zip
+	ls -l $PWD/$(basename "$ISO" .iso).zip
 	umount $mnt
 	rm -rf $mnt
 }
@@ -802,22 +802,22 @@ missing()
 
 ishybrid()
 {
-	[ $(get 510 $ISO) -eq 43605 ] || return
-	C=$((2048*$(get $(((17*2048) + 71)) $ISO 4)))
-	[ $(get $C $ISO 4) -eq 1 ] || return
-	[ $(get $(($C+30)) $ISO 4) -eq $((0x88AA55)) ] || return
-	C=$((2048*$(get $(($C+40)) $ISO 4)))
-	[ $(get $(($C+64)) $ISO 4) -eq 1886961915 ] && menuitem "$@"
+	[ $(get 510 "$ISO") -eq 43605 ] || return
+	C=$((2048*$(get $(((17*2048) + 71)) "$ISO" 4)))
+	[ $(get $C "$ISO" 4) -eq 1 ] || return
+	[ $(get $(($C+30)) "$ISO" 4) -eq $((0x88AA55)) ] || return
+	C=$((2048*$(get $(($C+40)) "$ISO" 4)))
+	[ $(get $(($C+64)) "$ISO" 4) -eq 1886961915 ] && menuitem "$@"
 }
 
 isiso()
 {
-	[ $(get 32769 $ISO 4) -eq 808469571 ] && menuitem "$@"
+	[ $(get 32769 "$ISO" 4) -eq 808469571 ] && menuitem "$@"
 }
 
 hastazboot()
 {
-	[ $(get 0 $ISO) -eq 23117 ] && menuitem "$@"
+	[ $(get 0 "$ISO") -eq 23117 ] && menuitem "$@"
 }
 
 burnable()
@@ -844,23 +844,39 @@ blankcd()
 gotisomd5()
 {
 	[ "$(which md5sum 2> /dev/null)" ] &&
-	[ $(get 0 $ISO) -eq 23117 ] &&
-	[ $(get 18 $ISO) -ne 0 ] && menuitem "$@"
+	[ $(get 0 "$ISO") -eq 23117 ] &&
+	[ $(get 18 "$ISO") -ne 0 ] && menuitem "$@"
 }
 
 isomd5()
 {
 	dotwait "Checking iso image"
-	[ "$(ddq if=$ISO bs=2k skip=16 \
-	     count=$(echo $(get 32848 $ISO 4)) | md5sum)" == \
-	  "$(ddq if=$ISO bs=16 count=1 skip=2047 | od -N 16 -t x1 -An | \
+	[ "$(ddq if="$ISO" bs=2k skip=16 \
+	     count=$(echo $(get 32848 "$ISO" 4)) | md5sum)" == \
+	  "$(ddq if="$ISO" bs=16 count=1 skip=2047 | od -N 16 -t x1 -An | \
 	     sed 's/ //g')  -" ] && echo "OK" || echo "ERROR"
 	echo -en "\rChecking iso hybrid boot..."
-	n=$(($(get 2 $ISO)-1+($(get 4 $ISO)-1)*512))
+	n=$(($(get 2 "$IS"O)-1+($(get 4 "$ISO")-1)*512))
 	if [ $n -lt 40000 -a $n -gt 32768 ]; then
-		s=$(get 0 $ISO 2 $n | awk '{ i+= $0 } END { print i }')
-		[ $(((1+$s+$(get $(($n+1)) $ISO 1)) % 65536)) -eq 0 ] &&
+		s=$(get 0 "$ISO" 2 $n | awk '{ i+= $0 } END { print i }')
+		[ $(((1+$s+$(get $(($n+1)) "$ISO" 1)) % 65536)) -eq 0 ] &&
 		echo "OK" || echo "ERROR"
+	fi
+	n=$(($(get 32848 "$ISO" 4)+16))
+	if [ "$(ddq bs=2k skip=$n if="$ISO" | ddq bs=1 count=6)" == "#!boot" ]; then
+		echo -en "\rChecking iso custum boot..."
+		md5="$(ddq bs=2k skip=$n if="$ISO" | while read line; do
+			case "$line" in
+			\#!boot*) echo ${line#*boot } > /tmp/$0$$md5 ;;
+			append=*) echo $line ;;
+			initrd:*) echo $line
+				  ddq bs=1 count=${line#initrd:}
+				  break ;;
+			*)	  break ;;	  
+			esac
+		done | md5sum | cut -c1-32)"
+		[ "$md5" == "$(cat /tmp/$0$$md5)" ] && echo "OK" || echo "ERROR"
+		rm -f /tmp/$0$$md5
 	fi
 	rm -f /tmp/wait
 	[ "$1" ] && return 0
@@ -923,8 +939,8 @@ $(tazusbmsg)Please plug your USB stick in now.\n
 		usbdev || return
 	
 		# perform dd in progress bar
-		max=$(($(stat -c %s $ISO)/2048))
-		i=0; ddq if=$ISO bs=1024k | ( 
+		max=$(($(stat -c %s "$ISO")/2048))
+		i=0; ddq if="$ISO" bs=1024k | ( 
 		while ddq bs=1024k count=1 ; do 
 			i=$(($i + 1))
 			[ $i -gt $max ] && break
@@ -994,7 +1010,7 @@ in the USB key." 14 70 4 \
 	exec 3>&-
 	[ $retval -eq 0 ] || return
 	[ "$format" != "none" ] && tazusb format $device "SliTaz" $format
-	tazusb gen-iso2usb $ISO $device
+	tazusb gen-iso2usb "$ISO" $device
 }
 
 dokexec()
@@ -1015,8 +1031,8 @@ runpxe()
 
 flavdata()
 {
-	[ $(get 1024 $ISO) -eq 35615 ] && n=2 || n=$((1+$(get 417 $ISO 1)))
-	dd if=$ISO bs=512 skip=$n count=20 2>/dev/null | zcat 2>/dev/null
+	[ $(get 1024 "$ISO") -eq 35615 ] && n=2 || n=$((1+$(get 417 "$ISO" 1)))
+	dd if="$ISO" bs=512 skip=$n count=20 2>/dev/null | zcat 2>/dev/null
 }
 
 hasflavinfo()
@@ -1053,7 +1069,7 @@ flavor()
 {
 	name="$(flavdata | cpio -t 2> /dev/null | sed 's/.[a-z]*$//;q')"
 	echo "Create ${name:=flavor}.flavor..."
-	tazlito iso2flavor $ISO $name
+	tazlito iso2flavor "$ISO" $name
 	ls -l $name.flavor
 }
 
@@ -1222,15 +1238,15 @@ quit()
 
 isotitle()
 {
-	echo "$(basename $ISO)  $(stat -c %y $media/.|sed 's/ .*//')  $(blkid \
-		$ISO | sed 's/.*LABEL="\([^"]*\).*/\1/')"
+	echo "$(basename "$ISO")  $(stat -c %y $media/.|sed 's/ .*//')  $(blkid \
+		"$ISO" | sed 's/.*LABEL="\([^"]*\).*/\1/')"
 }
 
 ISO="${1:-/dev/null}"
 [ -z "$(isiso 2> /dev/null)" ] && echo "Usage : $0 file.iso" && exit 1
 media=/tmp/media$$
 mkdir -p $media
-mount -o loop,ro $ISO $media
+mount -o loop,ro "$ISO" $media
 
 if [ "$2" == "list" ]; then
 	sed '/^\$(.*") \\/!d;s/^\$(\(.*\)").*/\1"/' $0 | while read line; do
