Remove ashism ==

diff --git a/syslinux/stuff/iso2exe/taziso b/syslinux/stuff/iso2exe/taziso
--- a/syslinux/stuff/iso2exe/taziso
+++ b/syslinux/stuff/iso2exe/taziso
@@ -844,7 +844,7 @@ customsector()
 hascustomconf()
 {
 	[ "$(ddq bs=2k skip=${1:-$(customsector)} if="$ISO" | ddq bs=1 count=6)" \
-	  == "#!boot" ]
+	  = "#!boot" ]
 }
 
 gotcustomconf()
@@ -887,7 +887,7 @@ isomd5()
 {
 	dotwait "Checking iso image"
 	[ "$(ddq if="$ISO" bs=2k skip=16 \
-	     count=$(($(get 32848 "$ISO" 4)-16)) | md5sum)" == \
+	     count=$(($(get 32848 "$ISO" 4)-16)) | md5sum)" = \
 	  "$(ddq if="$ISO" bs=16 count=1 skip=2047 | od -N 16 -t x1 -An | \
 	     sed 's/ //g')  -" ] && echo "OK" || echo "ERROR"
 	echo -en "\rChecking iso hybrid boot..."
@@ -912,7 +912,7 @@ isomd5()
 			*)	  break ;;
 			esac
 		done | md5sum | cut -c1-32)"
-		[ "$md5" == "$(cat $TMP)" ] && echo "OK" || echo "ERROR"
+		[ "$md5" = "$(cat $TMP)" ] && echo "OK" || echo "ERROR"
 		rm -f $TMP
 	fi
 	rm -f /tmp/wait
@@ -1070,7 +1070,7 @@ flavdata()
 
 hasflavinfo()
 {
-	[ "$(flavdata | ddq bs=1 count=7 | strings)" == \
+	[ "$(flavdata | ddq bs=1 count=7 | strings)" = \
 	  "0707010" ] && menuitem "$@"
 }
 
@@ -1109,7 +1109,7 @@ flavor()
 	read n
 }
 
-if [ "$1" == "--build" ]; then	#install-begin
+if [ "$1" = "--build" ]; then	#install-begin
 	uuencode -m - < ifmem.bin | sed -e '/^ifmemcode$/r/dev/stdin' \
 	  -e '/^ifmemcode$/d' -i $0
 	uuencode -m - < bootloader.bin | sed -e '/^bootloader$/r/dev/stdin' \
@@ -1311,7 +1311,7 @@ isotitle()
 		-c %y $media/.|sed 's/ .*//')  $(basename "$ISO")"
 }
 
-if [ "$1" == "include" ]; then
+if [ "$1" = "include" ]; then
 	[ -s "$2" ] && cd $(dirname "$2") && awk -v exe=$0 \
 	'{ if ($1 == "include") system(exe " include " $2); else print }' <"$2"
 	exit
@@ -1323,7 +1323,7 @@ media=/tmp/media$$
 mkdir -p $media
 mount -o loop,ro "$ISO" $media
 
-if [ "$2" == "list" ]; then
+if [ "$2" = "list" ]; then
 	sed '/^\$(.*") \\/!d;s/^\$(\(.*\)").*/\1"/' $0 | while read line; do
 		eval $line
 		echo
