get-*: do not create empty packages

diff --git a/get-OpenOffice3/stuff/get-OpenOffice3 b/get-OpenOffice3/stuff/get-OpenOffice3
--- a/get-OpenOffice3/stuff/get-OpenOffice3
+++ b/get-OpenOffice3/stuff/get-OpenOffice3
@@ -29,7 +29,7 @@ TARBALL="OOo_${VERSION}_${SUFFIX}"
 WGET_URL=ftp://ftp.proxad.net/mirrors/ftp.openoffice.org/$DIR/$VERSION/$TARBALL
 
 TEMP_DIR="/tmp/$PACKAGE.$$"
-SOURCE_DIR="/tmp/src"
+SOURCE_DIR="/tmp/src.$$"
 EXCLUDE="kde|gnome|test"
 LOG="/tmp/$(basename $0 .sh).log"
 
@@ -94,6 +94,11 @@ if [ ! -f $SOURCE_DIR/$TARBALL ]; then
 	# Get the file.
 	wget -c $WGET_URL -O $SOURCE_DIR/$TARBALL
 	status
+fi
+if [ ! -f $SOURCE_DIR/$TARBALL ]; then
+	rm -rf $SOURCE_DIR
+	echo "Could not download $TARBALL. Exiting."
+	exit 1
 fi
 
 # Creates TEMP_DIR and extract tarball
@@ -166,5 +171,6 @@ tazpkg pack $PACKAGE-$VERSION
 tazpkg install $PACKAGE-$VERSION.tazpkg --root=$ROOT
 
 # Clean
+rm -rf $SOURCE_DIR
 rm -rf $TEMP_DIR
 rm -rf $PACKAGE-$VERSION
diff --git a/get-dropbox/stuff/get-dropbox b/get-dropbox/stuff/get-dropbox
--- a/get-dropbox/stuff/get-dropbox
+++ b/get-dropbox/stuff/get-dropbox
@@ -30,6 +30,13 @@ cd $TEMP_DIR
 # Download the file
 wget $URL 
 
+if [ ! -f $TARBALL ]; then
+	echo "Could not download $TARBALL. Exiting."
+	cd $CUR_DIR
+	rm -rf $TEMP_DIR
+	exit 1
+fi
+
 tar xzf $TARBALL
 mkdir -p $PACKAGE-$VERSION/fs/usr/lib \
 	$PACKAGE-$VERSION/fs/usr/bin \
diff --git a/get-dsl-firmware/stuff/get-dsl-firmware b/get-dsl-firmware/stuff/get-dsl-firmware
--- a/get-dsl-firmware/stuff/get-dsl-firmware
+++ b/get-dsl-firmware/stuff/get-dsl-firmware
@@ -9,17 +9,18 @@ TMP=/tmp/$(basename $0)$$
 case "$MODULE" in
 speedtouch|speedtouch-silver|speedtch)
 	VERSION="3.012"
+	TARBALL="SpeedTouch330_firmware_$(echo $VERSION | sed 's/\.//').zip"
 	SHORT_DESC="Firmware for SpeedTouch ADSL Modem."
 	WEB_SITE="http://www.linux-usb.org/SpeedTouch/"
-	URL="http://www.speedtouch.com/download/drivers/USB"
-	URL="$URL/SpeedTouch330_firmware_$(echo $VERSION | sed 's/\.//').zip"
+	URL="http://www.speedtouch.com/download/drivers/USB/$TARBALL"
 	;;
 ueagle|ueagle-atm)
 	VERSION="1.1"
+	TARBALL="ueagle-data-$VERSION.tar.gz"
 	SHORT_DESC="Firmware for Fast800 USB ADSL Modem."
 	SOURCE="ueagle-data"
 	WEB_SITE="http://eagle-usb.org/"
-	URL="${WEB_SITE}ueagle-atm/non-free/ueagle-data-$VERSION.tar.gz"
+	URL="${WEB_SITE}ueagle-atm/non-free/$TARBALL"
 	;;
 *)	echo "Unknown dsl driver. Please run one of the following commands:"
 	for i in $(cd $(dirname $0); ls get-*-firmware); do
@@ -78,6 +79,13 @@ ueagle|ueagle-atm)
 		$PKG-$VERSION/fs/lib/firmware/ueagle-atm/CMV4p.bin || true
 	;;
 esac
+
+if [ ! -f $TARBALL ]; then
+	echo "Could not download $TARBALL. Exiting."
+	cd $TOP
+	rm -rf $TMP
+	exit 1
+fi
 
 # Create receipt
 cat > $PKG-$VERSION/receipt <<EOT
diff --git a/get-eclipse-pdt/stuff/get-eclipse-pdt b/get-eclipse-pdt/stuff/get-eclipse-pdt
--- a/get-eclipse-pdt/stuff/get-eclipse-pdt
+++ b/get-eclipse-pdt/stuff/get-eclipse-pdt
@@ -78,7 +78,12 @@ if [ ! -f $SOURCE_DIR/$TARBALL ]; then
 	status
 fi
 
-
+if [ ! -f $SOURCE_DIR/$TARBALL ]; then
+	rm -rf $TEMP_DIR
+	rm -rf $PACKAGE-$VERSION
+	echo "Could not download $TARBALL. Exiting."
+	exit 1
+fi
 
 # Creates TEM_DIR and extract tarball
 mkdir -p $TEMP_DIR
diff --git a/get-flash-plugin/stuff/get-flash-plugin b/get-flash-plugin/stuff/get-flash-plugin
--- a/get-flash-plugin/stuff/get-flash-plugin
+++ b/get-flash-plugin/stuff/get-flash-plugin
@@ -46,6 +46,11 @@ esac
 DIR=install_flash_player_${value}_linux
 TARBALL=$DIR.tar.gz
 [ -f $TARBALL ] || wget $URL$TARBALL
+if [ ! -f $TARBALL ]; then
+	echo "Could not download $TARBALL. Exiting."
+	exit 1
+fi
+
 
 # Extract
 mkdir $DIR
diff --git a/get-google-chrome/stuff/get-google-chrome b/get-google-chrome/stuff/get-google-chrome
--- a/get-google-chrome/stuff/get-google-chrome
+++ b/get-google-chrome/stuff/get-google-chrome
@@ -27,6 +27,12 @@ cd $TEMP_DIR
 
 # Download the file
 wget $URL 
+if [ ! -f $DEBPKG ]; then
+	cd $CUR_DIR
+	rm -rf $TEMP_DIR
+	echo "Could not download $DEBPKG. Exiting."
+	exit 1
+fi
 
 ar x $DEBPKG control.tar.gz data.tar.lzma && lzma d data.tar.lzma -so | tar xf -
 tar xzf control.tar.gz ./control
diff --git a/get-google-earth/stuff/get-google-earth b/get-google-earth/stuff/get-google-earth
--- a/get-google-earth/stuff/get-google-earth
+++ b/get-google-earth/stuff/get-google-earth
@@ -21,6 +21,13 @@ mkdir -p $TMP_DIR && cd $TMP_DIR
 
 # Download tarball
 wget http://dl.google.com/earth/client/current/GoogleEarthLinux.bin
+if [ ! -f GoogleEarthLinux.bin ]; then
+	cd $CUR_DIR
+	rm -rf $TMP_DIR
+	echo "Could not download GoogleEarthLinux.bin. Exiting."
+	exit 1
+fi
+
 chmod +x GoogleEarthLinux.bin
 sed -i 's/bzip2 -d/bunzip2/g' GoogleEarthLinux.bin
 
diff --git a/get-java6-jre/stuff/get-java6-jre b/get-java6-jre/stuff/get-java6-jre
--- a/get-java6-jre/stuff/get-java6-jre
+++ b/get-java6-jre/stuff/get-java6-jre
@@ -28,11 +28,18 @@ fi
 
 
 # Create TEMP_DIR
+CUR_DIR=$(pwd)
 test -d $TEMP_DIR || mkdir $TEMP_DIR
 cd $TEMP_DIR
 
 # Doanload the file
 test -f $TARBALL || wget $URL -O $TARBALL
+if [ ! -f $TARBALL ]; then
+	cd $CUR_DIR
+	rm -rf $TEMP_DIR
+	echo "Could not download $TARBALL. Exiting."
+	exit 1
+fi
 
 # Do not trust 'df' free space
 sed -i 's/exit 3$//' $TARBALL
@@ -87,11 +94,5 @@ tazpkg pack $PACKAGE-$VERSION
 tazpkg install $PACKAGE-$VERSION.tazpkg --root=$ROOT
 
 # Clean
-cd /tmp
+cd $CUR_DIR
 rm -rf $TEMP_DIR
-
-
-
-
-
-
diff --git a/get-libstdc++5/stuff/get-libstdc++5 b/get-libstdc++5/stuff/get-libstdc++5
--- a/get-libstdc++5/stuff/get-libstdc++5
+++ b/get-libstdc++5/stuff/get-libstdc++5
@@ -33,6 +33,12 @@ for i in $(dl_urls); do
 	DEB=$(basename $i)
 	wget $i && break
 done
+if [ ! -f $DEB ]; then
+	cd $CUR_DIR
+	rm -rf $TMP_DIR
+	echo "Could not download $DEB. Exiting."
+	exit 1
+fi
 
 VERSION=$(echo $DEB  | sed 's/.*_\(.*\)_.*/\1/')
 
diff --git a/get-linuxqq/stuff/get-linuxqq b/get-linuxqq/stuff/get-linuxqq
--- a/get-linuxqq/stuff/get-linuxqq
+++ b/get-linuxqq/stuff/get-linuxqq
@@ -29,6 +29,12 @@ cd $TEMP_DIR
 
 # Download the file
 wget $URL 
+if [ ! -f $RPMPKG ]; then
+	cd $CUR_DIR
+	rm -rf $TEMP_DIR
+	echo "Could not download $RPMPKG. Exiting."
+	exit 1
+fi
 
 rpm2cpio $RPMPKG | cpio -dium
 mkdir -p $PACKAGE-$VERSION/fs
diff --git a/get-opera/stuff/get-opera b/get-opera/stuff/get-opera
--- a/get-opera/stuff/get-opera
+++ b/get-opera/stuff/get-opera
@@ -31,6 +31,12 @@ URL=$URL$N/$RELEASE/en/i386/
 FILE=$(wget -O - $URL 2> /dev/null | grep rpm | sed 's|.*href="\(.*\)".*|\1|')
 URL=$URL$FILE
 wget $URL
+if [ ! -f $FILE ]; then
+	cd $CUR_DIR
+	rm -rf $TMP_DIR
+	echo "Could not download $FILE. Exiting."
+	exit 1
+fi
 
 VERSION=$(rpm -qip $FILE  | awk '/^Version/ { print $3 }')-$RELEASE
 
diff --git a/get-realplayer/stuff/get-realplayer b/get-realplayer/stuff/get-realplayer
--- a/get-realplayer/stuff/get-realplayer
+++ b/get-realplayer/stuff/get-realplayer
@@ -29,6 +29,12 @@ cd $TEMP_DIR
 
 # Download the file
 wget $URL 
+if [ ! -f $TARBALL ]; then
+	cd $CUR_DIR
+	rm -rf $TEMP_DIR
+	echo "Could not download $TARBALL. Exiting."
+	exit 1
+fi
 
 # Run the install. --help for options. Unable to surpress mozilla plugins install?
 chmod +x  $TARBALL
diff --git a/get-sjphone/stuff/get-sjphone b/get-sjphone/stuff/get-sjphone
--- a/get-sjphone/stuff/get-sjphone
+++ b/get-sjphone/stuff/get-sjphone
@@ -16,7 +16,8 @@ fi
 
 WEB_SITE="http://www.sjlabs.com/"
 VERSION="1.60.299"
-URL="http://www.sjphone.org/softphone/SJphoneLnx-299a.tar.gz"
+TARBALL="SJphoneLnx-299a.tar.gz"
+URL="http://www.sjphone.org/softphone/$TARBALL"
 
 TMP_DIR=/tmp/get-sjphone-$$-$RANDOM
 CUR_DIR=$(pwd)
@@ -24,9 +25,15 @@ mkdir -p $TMP_DIR && cd $TMP_DIR
 
 # Download tarball
 wget $URL
+if [ ! -f $TARBALL ]; then
+	cd $CUR_DIR
+	rm -rf $TMP_DIR
+	echo "Could not download $TARBALL. Exiting."
+	exit 1
+fi
 
 # Extract
-tar xzf $(basename $URL)
+tar xzf $TARBALL
 
 # Install files
 dir=sjphone-$VERSION/fs
diff --git a/get-skype/stuff/get-skype b/get-skype/stuff/get-skype
--- a/get-skype/stuff/get-skype
+++ b/get-skype/stuff/get-skype
@@ -17,10 +17,15 @@ fi
 
 # Download tarball
 WEB_SITE="http://www.skype.com/"
-wget ${WEB_SITE}go/getskype-linux-static
+TARBALL="getskype-linux-static"
+wget ${WEB_SITE}go/$TARBALL
+if [ ! -f $TARBALL ]; then
+	echo "Could not download $TARBALL. Exiting."
+	exit 1
+fi
 
 # Extract
-TARBALL=$(ls getskype-linux-static skype*.tar.bz2 2> /dev/null || true)
+TARBALL=$(ls $TARBALL skype*.tar.bz2 2> /dev/null || true)
 tar xjf $TARBALL
 VERSION=$(ls -d skype_static-*/)
 VERSION=${VERSION%/}
diff --git a/get-texlive/stuff/get-texlive b/get-texlive/stuff/get-texlive
--- a/get-texlive/stuff/get-texlive
+++ b/get-texlive/stuff/get-texlive
@@ -44,8 +44,14 @@ cd $TMP
 # Get files
 echo -e "\033[1;33m Getting $PACKAGE install script\033[0m"
 wget $WGET_URL
-tar -xzf $TARBALL
+if [ ! -f $TARBALL ]; then
+	cd $TOP
+	rm -rf $TMP
+	echo "Could not download $TARBALL. Exiting."
+	exit 1
+fi
 
+tar -xzf $TARBALL
 
 # launch texlive install script
 echo -e "\033[1;33m Launching $PACKAGE install script\033[0m" 
diff --git a/get-unace/stuff/get-unace b/get-unace/stuff/get-unace
--- a/get-unace/stuff/get-unace
+++ b/get-unace/stuff/get-unace
@@ -30,6 +30,12 @@ cd $DIR
 
 # Download tarball
 wget $WGET_URL
+if [ ! -f $TARBALL ]; then
+	cd $BASE
+	rm -rf $DIR
+	echo "Could not download $TARBALL. Exiting."
+	exit 1
+fi
 
 # Extract
 tar xzf $TARBALL
diff --git a/get-wifi-firmware/stuff/get-wifi-firmware b/get-wifi-firmware/stuff/get-wifi-firmware
--- a/get-wifi-firmware/stuff/get-wifi-firmware
+++ b/get-wifi-firmware/stuff/get-wifi-firmware
@@ -113,13 +113,21 @@ mkdir $TMP
 TOP=$PWD
 cd $TMP
 wget $WGET_URL
+TARBALL="$(basename $WGET_URL)"
+if [ ! -f $TARBALL ]; then
+	cd $TOP
+	rm -rf $DIR
+	echo "Could not download $TARBALL. Exiting."
+	exit 1
+fi
+
 case "$WGET_URL" in
-*rpm)	rpm2cpio < $(basename $WGET_URL) | cpio -id;;
-*deb)	dpkg-deb -x $(basename $WGET_URL) . ;;
-*bz2)	tar xjf $(basename $WGET_URL)
+*rpm)	rpm2cpio < $TARBALL | cpio -id;;
+*deb)	dpkg-deb -x $TARBALL . ;;
+*bz2)	tar xjf TARBALL
 	cd $SUBDIR/driver;;
-*tar.gz|*tgz)	tar xzf $(basename $WGET_URL);;
-*zip)	unzip $(basename $WGET_URL);;
+*tar.gz|*tgz)	tar xzf $TARBALL;;
+*zip)	unzip $TARBALL;;
 *o)	;;
 esac
 	
diff --git a/get-wink/stuff/get-wink b/get-wink/stuff/get-wink
--- a/get-wink/stuff/get-wink
+++ b/get-wink/stuff/get-wink
@@ -33,6 +33,12 @@ for i in $(dl_urls); do
 	TARBALL=$(basename $i)
 	wget $i && break
 done
+if [ ! -f $TARBALL ]; then
+	cd $CUR_DIR
+	rm -rf $TMP_DIR
+	echo "Could not download $TARBALL. Exiting."
+	exit 1
+fi
 
 VERSION=${TARBALL%.*}
 VERSION=${VERSION%.tar}
diff --git a/get-xlite/stuff/get-xlite b/get-xlite/stuff/get-xlite
--- a/get-xlite/stuff/get-xlite
+++ b/get-xlite/stuff/get-xlite
@@ -16,7 +16,6 @@ fi
 
 WEB_SITE="http://www.counterpath.net/"
 URL="http://counterpath.s3.amazonaws.com/downloads/X-Lite_Install.tar.gz"
-URLLIB="http://http.us.debian.org/debian/pool/main/g/gcc-3.3/libstdc++5_3.3.6-18_i386.deb"
 
 TMP_DIR=/tmp/get-xlite-$$-$RANDOM
 CUR_DIR=$(pwd)
@@ -24,7 +23,13 @@ mkdir -p $TMP_DIR && cd $TMP_DIR
 
 # Download tarball
 wget $URL
-wget $URLLIB
+TARBALL="$(basename $URL)"
+if [ ! -f $TARBALL ]; then
+	cd $CUR_DIR
+	rm -rf $TMP_DIR
+	echo "Could not download $TARBALL. Exiting."
+	exit 1
+fi
 
 # Extract
 tar xzf $(basename $URL)
@@ -46,8 +51,6 @@ Icon=firefox.png
 Type=Application
 Categories=Application;Network;
 EOT
-dpkg-deb -x $(basename $URLLIB) $dir
-rm -rf $dir/usr/share/doc
 
 # Create pseudo package
 cat > xlite-$VERSION/receipt <<EOT
@@ -59,7 +62,7 @@ WEB_SITE="$WEB_SITE"
 DEPENDS="atk cairo expat fontconfig freetype glib gtk+ libglade libpng libxml2 \
 pango pixman xorg-libX11 xorg-libXau xorg-libXcomposite xorg-libXcursor \
 xorg-libXdamage xorg-libXdmcp xorg-libXext xorg-libXfixes xorg-libXft \
-xorg-libXinerama xorg-libXrandr xorg-libXrender zlib"
+xorg-libXinerama xorg-libXrandr xorg-libXrender zlib libstdc++5"
 EOT
 
 # Pack
diff --git a/get-xnviewmp/stuff/get-xnviewmp b/get-xnviewmp/stuff/get-xnviewmp
--- a/get-xnviewmp/stuff/get-xnviewmp
+++ b/get-xnviewmp/stuff/get-xnviewmp
@@ -18,6 +18,11 @@ fi
 # Download tarball
 WEB_SITE="http://download.xnview.com"
 wget ${WEB_SITE}/XnViewMP-linux.tgz
+if [ ! -f $TARBALL ]; then
+	rm -rf XnViewMP
+	echo "Could not download $TARBALL. Exiting."
+	exit 1
+fi
 
 # Extract
 TARBALL=$(ls XnView*.tgz 2> /dev/null || true)
