Update: gcc+gcj (added package check)

diff --git a/gcc+gcj/receipt b/gcc+gcj/receipt
--- a/gcc+gcj/receipt
+++ b/gcc+gcj/receipt
@@ -13,7 +13,7 @@ xorg-libXcursor xorg-libXdamage xorg-libXdmcp xorg-libXext xorg-libXfixes \
 xorg-libXinerama xorg-libXrandr xorg-libXrender xorg-libXtst"
 BUILD_DEPENDS="glibc-dev gawk flex python perl gmp gmp-dev mpfr mpfr-dev \
 expat-dev zlib-dev zip unzip gtk+-dev libart_lgpl-dev xorg-dev xorg-inputproto \
-xorg-kbproto xorg-randrproto xorg-renderproto xorg-xextproto xorg-xproto"
+xorg-kbproto xorg-libXtst xorg-randrproto xorg-renderproto xorg-xextproto xorg-xproto"
 TARBALL="$SOURCE-$VERSION.tar.bz2"
 WEB_SITE="http://gcc.gnu.org/"
 WGET_URL="$GNU_MIRROR/$SOURCE/$SOURCE-$VERSION/$TARBALL"
@@ -22,6 +22,12 @@ PROVIDE="$SOURCE"
 # Rules to configure and make the package.
 compile_rules()
 {
+	# NOTE: gcj/libjava doesn't seem to build successfully when fastjar is installed
+	if [ -n "$(tazpkg list | grep '^fastjar\>')" ] ; then
+		echo "ERROR: Package 'fastjar' must be removed before compiling $PACKAGE"
+		exit 1
+	fi
+	
 	# Set BUILD_HOST if not defined in tazwok.conf as it should be
 	if [ -z "$BUILD_HOST" ] ; then
 		BUILD_HOST="i486-pc-linux-gnu"
