syslinux: fix kbd check (again)

diff --git a/syslinux/receipt b/syslinux/receipt
--- a/syslinux/receipt
+++ b/syslinux/receipt
@@ -90,7 +90,7 @@ MENU END
 EOT
     sed -i 's/^LABEL us$/&\n	MENU DEFAULT/' $fs/boot/isolinux/i18n.cfg
     for kbd in $(cd $src ; ls *.kbd); do
-    	[ -s $kbd ] || echo "Invalid file $kbd"
+    	[ -s $src/$kbd ] || echo "Invalid file $kbd"
     	grep -q " $kbd " $fs/boot/isolinux/i18n.cfg && continue
     	echo "Missing: file $kbd"
     done
