syslinux: fix kbd check

diff --git a/syslinux/receipt b/syslinux/receipt
--- a/syslinux/receipt
+++ b/syslinux/receipt
@@ -90,9 +90,9 @@ MENU END
 EOT
     sed -i 's/^LABEL us$/&\n	MENU DEFAULT/' $fs/boot/isolinux/i18n.cfg
     for kbd in $(cd $src ; ls *.kbd); do
-    	[ -s $kbd.kbd ] || echo "Invalid file $kbd.kbd"
-    	grep -q " $kbd.kbd " $fs/boot/isolinux/i18n.cfg && continue
-    	echo "Missing: file $kbd.kbd"
+    	[ -s $kbd ] || echo "Invalid file $kbd"
+    	grep -q " $kbd " $fs/boot/isolinux/i18n.cfg && continue
+    	echo "Missing: file $kbd"
     done
     chown root.root $fs/boot/isolinux/*
 }
